#!/bin/bash

# Directories for wallpapers
DIR=$HOME/Pictures/wallpapers-redblizard/

# Randomly select a wallpaper
PICS=($(find ${DIR} -type f -name "*.jpg" -o -name "*.png" -o -name "*.gif"))
RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}

# Terminate any existing swaybg processes if running
if [[ $(pidof swaybg) ]]; then
  pkill swaybg
fi

# Initialize or check if swww is running
swww query || swww init

# Change wallpaper using swww with transition effects
swww img "$RANDOMPICS" --transition-step 20 --transition-fps=20

# Generate color scheme with pywal
wal -c
wal -i "$RANDOMPICS"

# Uncomment the following line if you use Firefox with pywalfox extension
# pywalfox update

# Optionally clear the swww cache (comment out if not needed)
# rm -rf $HOME/.cache/swww
