#!/bin/bash

# Define the lock file
lock_file="$HOME/.config/hypr/scripts/welcome_flag"

# Check if the lock file exists
if [ -e "$lock_file" ]; then
    echo "Welcome script has already run. Exiting."
    exit 1
fi

# Your script's code goes here
echo "Starting hypr-welcome script..."
# This is where you would put the actual commands you want your script to run
# Example:
# ./path/to/hypr-welcome.sh
$HOME/.config/hypr/scripts/hypr-welcome

# Create the lock file
echo "Creating flag file..."
touch "$lock_file"

echo "Hypr-welcome script completed successfully."
