#!/usr/bin/env bash

# Flags:
# r: region
# s: screen
# c: clipboard
# f: file
# i: interactive
# p: pixel

show_help() {
    echo "Usage: $0 [option]"
    echo "Options:"
    echo "  rc    Take a region screenshot and copy to clipboard"
    echo "  rf    Take a region screenshot and save to file"
    echo "  ri    Take a region screenshot and open in Swappy"
    echo "  sc    Take a full screen screenshot and copy to clipboard"
    echo "  sf    Take a full screen screenshot and save to file"
    echo "  si    Take a full screen screenshot and open in Swappy"    
    echo "  -h    Show this help message"
}

case $1 in
    rc)
        grim -g "$(slurp -b '#000000b0' -c '#00000000')" - | wl-copy
        notify-send 'Copied to Clipboard' Screenshot
        ;;
    rf)
        mkdir -p ~/Pictures/Screenshots
        filename=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png
        grim -g "$(slurp -b '#000000b0' -c '#00000000')" "$filename"
        notify-send 'Screenshot Taken' "$filename"
        ;;
    ri)
        grim -g "$(slurp -b '#000000b0' -c '#00000000')" - | swappy -f -
        ;;
    sc)
        grim - | wl-copy
        notify-send 'Copied to Clipboard' Screenshot
        ;;
    sf)
        mkdir -p ~/Pictures/Screenshots
        filename=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png
        grim "$filename"
        notify-send 'Screenshot Taken' "$filename"
        ;;
    si)
        grim - | swappy -f -
        ;;
    -h|--help)
        show_help
        ;;
    *)
        notify-send "Invalid option" "Use -h or --help for usage information."
        show_help
        ;;
esac
