#!/bin/bash

flag_file="$HOME/.config/hypr/scripts/exec-once-flag"

if [ -f "$flag_file" ]; then
    echo "Flag exists. Removing it."
    rm "$flag_file"
else
    echo "Flag does not exist. Creating it."
    touch "$flag_file"
fi
