#!/bin/bash

# Config en style paden
CONFIG="$HOME/.config/wofi/drun-launcher/config"
STYLE="$HOME/.config/wofi/drun-launcher/style.css"

# Wofi run launcher
if ! pgrep -x "wofi" > /dev/null; then
    wofi --show run \
         --allow-images=true \
         --filter-rate=100 \
         --matching=fuzzy \
         --term=kitty \
         --width=950 \
         --height=342 \
         --columns=3 \
         -I \
         -c "$CONFIG" \
         -s "$STYLE"
else
    pkill wofi
fi
