#!/bin/bash

CONFIG="$HOME/.config/wofi/drun-launcher/config"
STYLE="$HOME/.config/wofi/drun-launcher/style.css"
WIDTH=950
HEIGHT=342

if [[ ! $(pidof wofi) ]]; then
  wofi --show drun \
       --allow-images=true \
       --filter-rate=100 \
       --matching=fuzzy \
       --term=alacritty \
       --width $WIDTH \
       --height $HEIGHT \
       --columns 3 \
       -I \
       -c "$CONFIG" \
       -s "$STYLE"
else
  pkill wofi
fi
