-- Generated by HyprMod


-- Monitors
hl.monitor({
    output = "desc:Panasonic Industry Company Panasonic-TV 0x01010101",
    mode = "1920x1080@60.00Hz",
    position = "1920x0",
    scale = 1,
    cm = "srgb",
})
